### ISSUE TITLE
sq1 global:* commands throw an origin directory error from Symfony

### ISSUE THREAD

**Issue by borkweb** [moderntribe/square1-global-docker#10]
**Describe the bug**
When attempting to run any of the `sq1 global:*` commands, the following error is thrown:

![Screen Shot 2020-04-14 at 8 26 49 AM](https://user-images.githubusercontent.com/430385/79224908-e3dea680-7e29-11ea-8c88-b7dd0ca389b7.png)

**To Reproduce**
First, I attempted a `sq1 self:update`, which seemed to work fine:

![Screen Shot 2020-04-14 at 8 28 56 AM](https://user-images.githubusercontent.com/430385/79224969-ffe24800-7e29-11ea-95bd-fdd791641afa.png)

When the error occurred after the update, I went ahead and re-ran the install script again (via the cURL):

![Screen Shot 2020-04-14 at 8 30 04 AM](https://user-images.githubusercontent.com/430385/79225057-2902d880-7e2a-11ea-9e3c-81c607277222.png)

**Expected behavior**
The expectation was that the global docker containers would start when running `sq1 global:start`

**Actual behavior**
This error occurred:

![Screen Shot 2020-04-14 at 8 26 49 AM](https://user-images.githubusercontent.com/430385/79224908-e3dea680-7e29-11ea-8c88-b7dd0ca389b7.png)

**System Configuration:**
 - OS: macOS 10.14.6
 - PHP Version 7.3.2

**Comment by borkweb** [comment]
It looks like the source of the error is here: https://github.com/moderntribe/square1-global-docker/blob/master/src/Hooks/Docker.php#L33

**Comment by defunctl** [comment]
Should be fixed in https://github.com/moderntribe/square1-global-docker/releases/tag/1.2.2-beta
