### ISSUE TITLE
host.tribe not pointing to the expected IP address on Mac OS Catalina 

### ISSUE THREAD

**Issue by ChrisMKindred** [moderntribe/square1-global-docker#17]
**Describe the bug**
On OSX Catalina, it appears that the host.tribe ip address is 172.17.0.1 but that address is unreachable outside the local container.  The host ip is actually 192.168.65.2.  This is causing xdebug to no connect unless provided the 192.168.65.2 address for the remote_host. I can't tell if it is because the ip address of the host should be getting changed, or if the Gateway IP address is from the `docker network inspect bridge` is returning an unexpected value.

**To Reproduce**
When using host.tribe as the `xdebug.remote_host`, no conection is made.  Update the remote host value to 192.168.65.2 and connection is successful.

**Expected behavior**
host.tribe should match the host ip address.

**System Configuration:**
 - OS: Mac OS Catalina
 - PHP Version: PHP 7.4.4

**Additional context**
This was the same issue I was running into first getting xdebug setup with square-one.  The alpine build we were using was cached on some systems and working fine but the version of alpine I received was not returning a consitant ip address when running `docker run --rm -it alpine nslookup docker.for.mac.localhost`. By forcing the 3.10 version of alpine we were able to fix the problem.  I am not sure if the two are related in this case but might help for troubleshooting.

**Comment by defunctl** [comment]
Fixed in https://github.com/moderntribe/square1-global-docker/releases/tag/2.0.2-beta
