### ISSUE TITLE
Attempt to set proper folder permissions

### ISSUE THREAD

**Issue by defunctl** [moderntribe/square1-global-docker#18]
https://devilbox.readthedocs.io/en/latest/readings/syncronize-container-permissions.html

Either making the owner in the container the same as the user (so PHP-FPM runs as that user), or also it's certainly possible to detect the host's http or www-data user and set that owner on the cache/uploads folders etc...

**Comment by Luc45** [comment]
I couldn't find much of the logic for this feature in devilbox itself, but I could find it in the php image that it uses, which is also theirs: https://github.com/devilbox/docker-php-fpm/blob/master/Dockerfiles/work/data/docker-entrypoint.sh

**Comment by defunctl** [comment]
Fixed with https://github.com/moderntribe/squareone-docker-images/ and https://github.com/moderntribe/square1-global-docker/pull/30 sets the proper UID/GID.
