### ISSUE TITLE
Flag to open project in browser on start

### ISSUE THREAD

**Issue by jbrinley** [moderntribe/square1-global-docker#23]
The `start` command opens a project in the browser after starting the containers. This behavior becomes a nuisance after the first couple of times it runs.

Can we wrap that step in a flag? E.g.: `so start --browser` / `so start -b`

**Comment by defunctl** [comment]
Updated in https://github.com/moderntribe/square1-global-docker/pull/22/commits/b96869fda95fbedd9e721973bfe6154c79e1c69a
