### ISSUE TITLE
New path for nginx config

### ISSUE THREAD

**Issue by jbrinley** [moderntribe/square1-global-docker#33]
**Describe the bug**
My nginx config for the global reverse proxy formerly lived in `~/.config/squareone/global/docker/nginx`. Version 3 expects the files in `~/.config/squareone/global/nginx`. When the global containers start, the reverse proxy fails to load.

```
ERROR: for tribe-proxy  Cannot start service reverse-proxy: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/jbrinley/.config/squareone/global/nginx/nginx.tmpl\\\" to rootfs \\\"/var/lib/docker/overlay2/8c4705dd900899cd3bccaeb70501ab877ee4190e3455d6c2cb4cd14f80a73823/merged\\\" at \\\"/var/lib/docker/overlay2/8c4705dd900899cd3bccaeb70501ab877ee4190e3455d6c2cb4cd14f80a73823/merged/app/nginx.tmpl\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

After copying the files from `global/docker/nginx` to `global/nginx`, I am able to proceed.

**Comment by defunctl** [comment]
Should be fixed in https://github.com/moderntribe/square1-global-docker/pull/30/commits/825d2ac2a3603d955512b07021abae80a0f1f453

**Comment by jbrinley** [comment]
Fixed
