### ISSUE TITLE
docker-compose.override.yml is ignored

### ISSUE THREAD

**Issue by jbrinley** [moderntribe/square1-global-docker#34]
**Describe the bug**
Docker Compose should respect the contents of `docker-compose.override.yml`. Instead the file is ignored. This happens when the `--file` argument is explicitly passed to `docker-compose up`; it overrides Docker Compose's default behavior. If we're going to be passing that argument, we also need to check for the presence of `docker-compose.override.yml` and pass it as an additional `--file` argument.

**Comment by defunctl** [comment]
Should be fixed in https://github.com/moderntribe/square1-global-docker/pull/30/commits/95cb26ff90b07b7a9008dc3164a5a279683b7651

**Comment by jbrinley** [comment]
Fixed
