### ISSUE TITLE
Install issue on Ubuntu fork distro, PopOS.

### ISSUE THREAD

**Issue by nickpelton** [moderntribe/square1-global-docker#37]
**Describe the bug**
After installing SO on PopOS Linux (based on Ubuntu) any so command fails. 

**To Reproduce**
What did you do?
1. Fresh linux distro. 
2. Installed PHP (7.4 is the distro latest). 
3. Ran `so` command. = Error

**Expected behavior**

`so` command should work and show help menu.

**Actual behavior**
```PHP Fatal error:  Uncaught TypeError: Return value of Tribe\SquareOne\Models\OperatingSystem::getLinuxFlavor() must be of the type string, bool returned in phar:///home/nick/.config/squareone/bin/so/src/Models/OperatingSystem.php:48
Stack trace:
#0 phar:///home/nick/.config/squareone/bin/so/src/Hooks/CertificateHandler.php(51): Tribe\SquareOne\Models\OperatingSystem->getLinuxFlavor()
#1 [internal function]: Tribe\SquareOne\Hooks\CertificateHandler->setDependencies()
#2 phar:///home/nick/.config/squareone/bin/so/vendor/league/container/src/Inflector/Inflector.php(100): call_user_func_array()
#3 phar:///home/nick/.config/squareone/bin/so/vendor/league/container/src/Inflector/InflectorAggregate.php(43): League\Container\Inflector\Inflector->inflect()
#4 phar:///home/nick/.config/squareone/bin/so/vendor/league/container/src/Container.php(290): League\Container\Inflector\InflectorAggregate->inflect()
#5 phar:///home/nick/.config/squareone/bin/so/vendor/league/container/src/Container.php(85): League\Container\Container->getFromThisC in phar:///home/nick/.config/squareone/bin/so/src/Models/OperatingSystem.php on line 48```

**System Configuration:**
 - OS: 
```NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 - PHP Version: 7.4.3

**Additional context**

**Comment by defunctl** [comment]
@nickpelton please use the release/3.0.0 branch, no more updates will be made to the old one. 

Because it hasn't been merged the dev-install script won't work but you should be able to follow along what it should be doing: https://github.com/moderntribe/square1-global-docker/blob/release/3.0.0/install/dev-install.sh

If you need help just reach out.

**Comment by defunctl** [comment]
Here are the steps just in case:

1. git clone https://github.com/moderntribe/square1-global-docker
1. git checkout release/3.0.0.
1. composer install 
1. sudo ln -s path/to/repo/so /usr/local/bin/sodev
1. type sodev

**Comment by nickpelton** [comment]
Closing. Will retest on latest 3.0
