### ISSUE TITLE
Create cert for test domain

### ISSUE THREAD

**Issue by jbrinley** [moderntribe/square1-global-docker#38]
**Describe the bug**
When spinning up a new project with `so create` or `so bootstrap`, a certificate will be autogenerated for the new `mydomain.tribe` domain. We also need a cert for `mydomaintest.tribe` for running automated tests.

**Comment by defunctl** [comment]
@jbrinley this should be the case already in 3.0.0: https://github.com/moderntribe/square1-global-docker/blob/release/3.0.0/app/Services/Certificate/Certificate.php#L105

Can you pull and confirm again on a project that has no cert or perhaps I need to add additional checks to look for that specific test cert and generate it.

**Comment by jbrinley** [comment]
The issue comes from the interplay between our project containers, the certs, and the reverse proxy. When a container starts, the proxy will update its nginx config to add hosts based on the `VIRTUAL_HOST` environment variable. If it finds a certificate with a file name matching the host name (e.g., `square1test.tribe.crt` for `square1test.tribe`, it will add a host on port 443, otherwise it just listens on 80.

There are two possible paths here:
1. Generate the certs separately
2. Update our docker-compose.yml to set the `CERT_NAME` environment variable for the test webserver, per https://github.com/nginx-proxy/nginx-proxy#sni

I like option #1 because it's more transparent what's happening. I like option #2 because then we don't need so many certificates.

If we go with #2, we need to have a way to specify other alternate names for the cert, in case the project is using a non-standard test domain (e.g., we recently had something like `client-project.tribe` and `clienttest.tribe` for the dev and test domains).

**Comment by defunctl** [comment]
I'll think this over. Regarding the non-standard project, I really think the project itself should be updated to match the standards of all others, using the name in `.projectID`.

**Comment by defunctl** [comment]
I think I'll go with option 1 here.

**Comment by defunctl** [comment]
@jbrinley should be fixed in https://github.com/moderntribe/square1-global-docker/pull/30/commits/1308e58e361f503eb79e4cb0f95dc698ab806615

**Comment by jbrinley** [comment]
Works great
