### ISSUE TITLE
`so create` nvm erorr

### ISSUE THREAD

**Issue by nickpelton** [moderntribe/square1-global-docker#42]
**Describe the bug**
When using `so create` to create a new project it threw an error when trying to call nvm.

**To Reproduce**
On a mac, run:
1. `so create`
2. follow steps
3. see error when it tries to run nvm

**Expected behavior**
I expect the project to complete and for the tool properly call nvm

**Actual behavior**
http://p.tri.be/LZrknl

**System Configuration:**
 - OS: MacOS
 - PHP Version: 7.3.7
- NVM: v12.16.2

**Additional context**
I'm guessing the issue is it's calling `nvm.sh` when it should call the global `nvm`

**Comment by defunctl** [comment]
@nickpelton what do you have in your `~/.zshrc` ?

```
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```
?

Does this command show any output `printenv | grep NVM_DIR` ?

**Comment by nickpelton** [comment]
```printenv | grep NVM_DIR
NVM_DIR=/Users/nick/.nvm```

**Comment by nickpelton** [comment]
```cat ~/.zshrc | grep nvm
export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion```

**Comment by defunctl** [comment]
Does `ls ~/.nvm` not show a `nvm.sh`?

**Comment by nickpelton** [comment]
correct, not there.
```ls ~/.nvm
alias    versions
```

**Comment by defunctl** [comment]
Alright, a work around for now should be:

```
ln -s /usr/local/opt/nvm/nvm.sh ~/.nvm/nvm.sh
```

**Comment by nickpelton** [comment]
Was a brew issue. Does not install NVM properly. brew is not the supported way of installing, using supported method worked and fixed issue. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash`
