### ISSUE TITLE
so create does too much

### ISSUE THREAD

**Issue by nickpelton** [moderntribe/square1-global-docker#43]
IMO, `so create` does too much. It should setup the project and push to the repo. That's it. Building assets and starting the servers were unexpected and should be different commands.

**Comment by defunctl** [comment]
Hey @nickpelton,

You already have this option with `so create --no-bootstrap`. Feel free to close the issue if that solves your problem.

**Comment by nickpelton** [comment]
Nice! Still feels like it should be opt-in. So I would prefer `so create --bootstrap`

**Comment by defunctl** [comment]
I went with the ideal that it should automatically do as much as it possibly can, with options to not do as much so those with a properly configured system will have a project ready to go with a single command.
