### ISSUE TITLE
Cannot copy from inside a phar file

### ISSUE THREAD

**Issue by mariacdadalt** [moderntribe/square1-global-docker#46]
**Describe the bug**
When "so start" for the first time, so gives me 
 cp: cannot stat 'phar:///home/maria/.config/squareone/bin/so/storage/dns/debian/resolved.conf': No such file or directory 

**To Reproduce**
Fresh ubuntu installation and running so for the first time. 

**Expected behavior**
so to start without problems.

**Actual behavior**
 cp: cannot stat 'phar:///home/maria/.config/squareone/bin/so/storage/dns/debian/resolved.conf': No such file or directory 

**System Configuration:**
 - OS: Ubuntu Linux
 - PHP Version 7.4

**Additional context**
Replacing /etc/systemd/resolved.conf
with https://github.com/moderntribe/square1-global-docker/blob/master/storage/dns/debian/resolved.conf
resolves the issue.

**Comment by defunctl** [comment]
Fixed in https://github.com/moderntribe/square1-global-docker/releases/tag/3.0.5
