### ISSUE TITLE
SO WP command doesn't recognize flags designated for WP-CLI

### ISSUE THREAD

**Issue by rwrobe** [moderntribe/square1-global-docker#49]
**Describe the bug**
When using `so` for a WP CLI command that includes a flag, e.g., `so wp user update tribe --user_pass=secretstuff`, `so` throws an error: 

The "--user_pass" option does not exist. 

**To Reproduce**

Run something like this `so wp user update tribe --user_pass=secretstuff`

**Expected behavior**

WP CLI commands should run with included flags, or some help text should explain the proper syntax.

**Comment by defunctl** [comment]
@rwrobe see https://github.com/moderntribe/square1-global-docker#run-a-wp-cli-command-in-the-php-fpm-container :)

**Comment by jbrinley** [comment]
I've found this to be a helpful alias:

```
alias wp='so wp --'
```
