### ISSUE TITLE
SO start fails without `resolv.conf.d/head`

### ISSUE THREAD

**Issue by rwrobe** [moderntribe/square1-global-docker#50]
**Describe the bug**
When running `so start` for a new project under `v3.0.5`, `so` fails if `resolv.conf.d/head` does not exist. This forces the user to manually create the file even if they use `/etc/hosts` for setting up nameservers.

**To Reproduce**
Enable NetwoikManager and set `/etc/NetworkManager/NetworkManager.conf` to:

```bash
[main]
plugins=ifupdown,keyfile
rc-manager=resolvconf
dns=default

[ifupdown]
managed=false

[device]
wifi.scan-rand-mac-address=no
```
Remove `resolv.conf.d/head`.

**Expected behavior**
`so` should skip adding the nameserver and display a message to the user to do so themself.

**Actual behavior**
`so` gives a generic failure message with error code 1 for the nameserver echo line.

**System Configuration:**
 - OS: [e.g. macOS, Ubuntu Linux]: Zorin (Ubuntu), stock NetworkManager config
 - PHP Version: 7.4.11

**Comment by defunctl** [comment]
Are you saying `so` isn't properly creating the head file with `nameserver 127.0.0.1` in it or are you manually removing the head file after it's created?

**Comment by amarsyla** [comment]
Had something similar related to this issue happening when I was setting up my environment during install. Instead of the `resolv.conf.d/head`, it was trying to setup the `/etc/resolvers` file which was not existing. I am on MacOS.

**Comment by defunctl** [comment]
I have some DNS/resolver updates coming that should address all of this :)

**Comment by defunctl** [comment]
Fixed in https://github.com/moderntribe/square1-global-docker/releases/tag/3.0.6
