### ISSUE TITLE
docker-compose Command Moving to Sub-Command

### ISSUE THREAD

**Issue by tarecord** [moderntribe/square1-global-docker#65]
After updating Docker Desktop, I noticed a new message indicating that `docker compose` is now available instead of the current `docker-compose`. It looks like they added this functionality [back in December](https://github.com/docker/compose-cli/releases/tag/v1.0.4) but may be moving to deprecate `docker-compose` in the future.

<img width="565" alt="Screenshot on 2021-04-16 at 15-49-33" src="https://user-images.githubusercontent.com/6947218/115084415-e1001100-9ed6-11eb-8083-2f8fac6ca483.png">

I think we could be proactive in this and do some refactoring around the `DockerCompose` Service.

**System Configuration:**
 - OS: macOS
 - SO Version: 4.0.0
 - Docker Desktop Version: 3.3.0 (62916)

**Comment by defunctl** [comment]
Note that outside of Mac & Windows this is only available in the tech preview: https://docs.docker.com/compose/cli-command/
