### ISSUE TITLE
so create missing dependency

### ISSUE THREAD

**Issue by RobertoGongora** [moderntribe/square1-global-docker#67]
![image](https://user-images.githubusercontent.com/1845147/117890287-84480a00-b27a-11eb-9737-e23f0c7e343d.png)

NVM isn't listed in the README as a requirement nor installed automatically by the curl script

**Comment by defunctl** [comment]
Thanks for the report, @RobertoGongora! NVM is a dependency for using SquareOne, but not specifically `so`.

Regardless, I've added it to the installers with https://github.com/moderntribe/square1-global-docker/commit/0c0e9debc1712ddfac33b094b0cad49d13ed8773
