### ISSUE TITLE
Using Big Sur's new virtualization binds port 53 automatically.

### ISSUE THREAD

**Issue by RobertoGongora** [moderntribe/square1-global-docker#68]
I had some issues setting this up on macOS, which turned out to be that I had the new Big Sur virtualization framework enabled (I feel it's more stable when using an M1 SoC), and Apple is using port 53 for *something* when using that. The solution was to disable it and use the "old" hypervisor.framework, but the errors weren't super obvious and took a bit of googling to find out.

Is there a way to either change the dnsmasq default port, or should we add a note for MacOS for now?

**Comment by defunctl** [comment]
Hey @RobertoGongora is it the issue in the Wiki Troubleshooting doc https://github.com/moderntribe/square1-global-docker/wiki/Troubleshooting#error-for-dns-external--cannot-start-service-dns-external ?

**Comment by RobertoGongora** [comment]
I'll try to apply the command and see if it plays well with the new virtualization framework, I'll update this issue accordingly!

**Comment by RobertoGongora** [comment]
This was fixed by the Docker team in a recent Docker for Mac release :)
