### ISSUE TITLE
so create miss-match password ux enhancement

### ISSUE THREAD

**Issue by nickpelton** [moderntribe/square1-global-docker#76]
**Describe the enhancement**
When running `so create project-name` the password prompt requires matching strings (of course). If they don't match it's a hard fail. Then running `so create project-name` doesn't work because the folder already exists. I would suggest we allow a re-try if passwords don't match rather than a hard fail that requires cleanup before trying again.

**To Reproduce**
1. `so create project-name`
2. Enter missmatched passwords as part of setup

**Expected behavior**
I expected the command to fail gracefully so I could run it again without cleanup OR a simple retry prompt.

**Actual behavior**
Miss matched passwords caused hard fail. To re-do the process, folder had to be deleted before a retry. 

**System Configuration:**
 - OS: OSX
 - PHP Version: PHP 7.4+

**Comment by defunctl** [comment]
Fixed in https://github.com/moderntribe/square1-global-docker/releases/tag/5.2.1
