### ISSUE TITLE
SO Update Notice Not Showing Correct Version

### ISSUE THREAD

**Issue by tarecord** [moderntribe/square1-global-docker#78]
**Describe the bug**
The version number listed in the update notice was not the same as the actual version installed.

**To Reproduce**
I was on a version of SO _before_ `5.1.0`

**Expected behavior**
After seeing the notice, I typed `so self:update` and expected to be updated to version `5.1.0` like the notice indicated.

**Actual behavior**
SO was updated to version `5.1.1`

**System Configuration:**
 - OS: macOS 11.4 (20F71)

**Additional context**
<img width="1085" alt="Screenshot on 2021-08-04 at 09-35-16" src="https://user-images.githubusercontent.com/6947218/128191059-288d694d-e8b3-4925-a705-6b8e94bbae8c.png">

**Comment by defunctl** [comment]
Much appreciated, thanks @tarecord

**Comment by defunctl** [comment]
Fixed in https://github.com/moderntribe/square1-global-docker/releases/tag/5.2.1
